general:
  use_uvloop: true

functions:
  internet_search:
    _type: tavily_internet_search
    description: "使用Tavily API进行实时网络搜索"
  
  pingan_search:
    _type: tavily_internet_search
    description: "使用Tavily API在平安保险官网(baoxian.pingan.com)进行搜索"
    max_results: 5
    url: "https://baoxian.pingan.com"

  current_datetime:
    _type: current_datetime
    description: "获取当前日期和时间"

llms:
  # 默认使用Bailian API (用户可修改)
  default_llm:
    _type: openai
    model_name: "qwen-plus"
    api_key: "sk-76875d587c1944a3ae299ce1d7ace977"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    temperature: 0.7
    max_tokens: 2048

workflow:
  _type: react_agent
  tool_names:
    - internet_search
    - current_datetime
    - pingan_search
  llm_name: default_llm
  verbose: true
  parse_agent_response_max_retries: 3
  max_iterations: 10

eval:
  general:
    output_dir: .tmp/nat/examples/react_agent/
    dataset:
      _type: json
      file_path: docs/insurance.json
  evaluators:
    rag_accuracy:
      _type: ragas
      metric: AnswerAccuracy
      llm_name: nim_llm
    rag_groundedness:
      _type: ragas
      metric: ContextRelevance
      llm_name: nim_llm
    rag_relevance:
      _type: ragas
      metric: ResponseGroundedness
      llm_name: nim_llm